config/routes.rb
Rails.application.routes.draw do
  get 'pages/game'
  get 'game', to: 'pages#game'

  get 'pages/score'
  get 'score', to: 'pages#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/longest_word.rb
require 'open-uri'
require 'json'
require 'time'

def generate_grid(grid_size)
  # TODO: generate random grid of letters
  grid_array = []
  grid_size.times { grid_array << [*'A'..'Z'].sample }
  grid_array
end

def run_game(attempt, grid, start_time, end_time)
  # TODO: runs the game and return detailed hash of result
  time_taken = end_time - start_time
  if word_checker(attempt) && in_the_grid(attempt, grid)
    return { time: time_taken, score: (attempt.size * 100) - (time_taken * 10), message: "well done" }
  elsif word_checker(attempt) == false && in_the_grid(attempt, grid) == true
    return { time: (end_time - start_time), score: 0, message: "not an english word" }
  else # word_checker(attempt) == true && in_the_grid(attempt, grid) == false
    return { time: (end_time - start_time), score: 0, message: "that's not in the grid" }
  end
  # result = { time: 10, score: 100, message: "Good job" }
  # p result
end

def word_checker(attempt)
  url = "https://wagon-dictionary.herokuapp.com/#{attempt}"
  word_serialized = open(url).read
  word = JSON.parse(word_serialized)
  word["found"]
end

def in_the_grid(attempt, grid)
  check = true
  attempt.upcase.chars.each do |letter|
    check = false unless grid.include? letter
    grid.delete(letter)
  end
  check
end

# p word_checker("swaggers")
# grid_checker(generate_grid(9), "welcome")
# grid_checker(["W","E","L","C","O","M","E","E","M"], "welcome")
# p run_game("WELCOME", ["W", "E", "L", "C", "O", "M", "E", "E", "M"], 10, 15)
# p run_game("HOI", ["H", "O", "I", "C", "O", "M", "E", "E", "M"], 10, 15)


# def grid_checker(grid, attempt)
#   # idea, make an hash of the complete alphabet, let them add if key in grid, deduct
#   # when in attempt. Values < 0 is an error
#   alphabet_hash = Hash.new(0)
#   alphabet_array = [*"A".."Z"]
#   alphabet_array.group_by(&:itself).each { |k, v| alphabet_hash[k] = 0 }
#   alphabet_hash
#   grid_hash = {}
#   attempt_hash = {}
#   attempt_array = attempt.chars
#   grid.group_by(&:itself).each { |k, v| grid_hash[k] = v.length }
#   attempt_array.group_by(&:itself).each { |k, v| attempt_hash[k] = v.length }
#   # p grid_hash
#   # p attempt_hash
#   # p attempt_array
#   # difference = (grid_hash.to_a - attempt_hash.to_a).to_h
#   # p difference
#   p sum_hash = (alphabet_hash.to_a + grid_hash.to_a).to_h
#   attempt_hash.each do |k, v|
#     sum_hash[k] = sum_hash[sum_hash[k]] - attempt_hash[v]
#   end
#   p sum_hash
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'open-uri'
  require 'json'
  require 'time'

  def game
    @grid = generate_grid(10)
    @start_time = Time.now
  end

  def score
    @end_time = Time.now
    @start_time2 = params[:game_start]
    @grid2 = params[:u_grid]
    @answer = params[:word]
    @score = run_game(@answer, @grid2, @start_time2, @end_time)
  end

  private

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a.sample }
  end

  def included?(guess, grid)
    guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    time_taken > 60.0 ? 0 : attempt.size * (1.0 - time_taken / 60.0) * 100
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: (end_time.to_time - start_time.to_time) }

    score_and_message = score_and_message(attempt, grid, result[:time])
    result[:score] = score_and_message.first
    result[:message] = score_and_message.last

    result
  end

  def score_and_message(attempt, grid, time)
    if included?(attempt.upcase, grid)
      if english_word?(attempt)
        score = compute_score(attempt, time).to_i
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def english_word?(word)
    response = open("https://wagon-dictionary.herokuapp.com/#{word}")
    json = JSON.parse(response.read)
    return json['found']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>

  <body>
  <div class="container" display="flex" justify-content="space-around">
    <div>
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/pages/game.html.erb
<h1>Longest Word Game</h1>
<p>Try to make the longest word with the given letters</p>


<% game_grid = @grid %>
<% start_time = @start_time %>
<!-- <p><%= @grid %></p> -->

<p><%= start_time %></p>

<br>
<br>

<h1>This is your grid</h1>
<ul class="list-inline">
<% game_grid.each do |letter| %>
  <li class="list-inline-item"><%= letter.capitalize %></li>
<% end %>
</ul>

<br>
<br>

<form action="/score">
  <label for="question">Give your answer</label>
  <input type="text" id="anwer_box" name="word" placeholder="Give your answer">
  <input type="hidden" id="used_grid" name="u_grid" value="<%= game_grid %>">
  <input type="hidden" id="start_time" name="game_start" value="<%= start_time %>">
  <input type="submit" value="Submit word!">
</form>

app/views/pages/score.html.erb
<h1><%= @score[:message] %></h1>

<h2>Your answer was: <%= @answer %></h2>
<p>It took you: <%= @score[:time].to_i %> seconds</p>
<h2>This results in a score of: <%= @score[:score] %> out of 1000</h2>

<%= link_to "Play again", game_path, { :class => "btn btn-primary" } %>